application: vendladder
version: foos-8-1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- login: admin
  script: google.appengine.ext.admin.application
  url: /admin/?.*

- url: /static
  static_dir: static

- login: admin
  url: /sc2/admin/.*
  script: main.app

- url: /.*
  script: main.app
